// Traffic Simulator — runs on the main thread via setInterval at 4 Hz.
// Pure TS, no React. Subscribers receive SimSnapshot every tick.
//
// Design:
//   - Each intersection owns a queue per approach (N/S/E/W).
//   - Vehicles are generated by a Poisson-ish random arrival per approach.
//   - When the light is green for an approach, vehicles dequeue at a fixed
//     throughput (cars-per-second), accumulating "passed" + wait stats.
//   - Two algorithms decide phase length:
//       * fixed   — 30s green per axis (NS then EW), 3s amber transitions.
//       * greedy  — green time scales with max queue on the active axis,
//                   clamped to [10s, 60s]. Switches axes when queues balance.
//   - Emergency override forces green for the ambulance's axis until the
//     ambulance clears the intersection, then restores normal cycle.

import {
  type Algorithm,
  type ApproachState,
  type Direction,
  DIRECTIONS,
  type IntersectionConfig,
  type IntersectionState,
  type SimSnapshot,
  type SimStats,
  type Vehicle,
} from "./types";

const TICK_HZ = 4;
const TICK_MS = 1000 / TICK_HZ;
const AMBER_DURATION = 3;          // seconds
const FIXED_GREEN = 30;            // seconds
const GREEDY_MIN_GREEN = 10;
const GREEDY_MAX_GREEN = 60;
const ARRIVAL_LAMBDA = 0.35;       // expected vehicles/sec per approach
const DISCHARGE_RATE = 1.2;        // vehicles/sec per green lane
const MAX_QUEUE = 40;

const isNSDir = (d: Direction) => d === "N" || d === "S";

function emptyApproach(d: Direction): ApproachState {
  return { direction: d, queueLength: 0, light: "red", remaining: 0 };
}

function configToState(c: IntersectionConfig): IntersectionState {
  const approaches = Object.fromEntries(
    DIRECTIONS.map((d) => [d, emptyApproach(d)]),
  ) as Record<Direction, ApproachState>;
  return {
    id: c.id,
    name: c.name,
    lat: c.lat,
    lng: c.lng,
    algorithm: c.algorithm,
    phase: "NS",
    phaseRemaining: FIXED_GREEN,
    approaches,
    passed: 0,
    totalWaitSeconds: 0,
    emergencyOverride: false,
  };
}

function setLights(state: IntersectionState) {
  const greenAxis = state.phase === "NS" || state.phase === "NS_AMBER" ? "NS" : "EW";
  const amber = state.phase.endsWith("AMBER");
  for (const d of DIRECTIONS) {
    const ns = isNSDir(d);
    const onAxis = ns ? greenAxis === "NS" : greenAxis === "EW";
    state.approaches[d].light = onAxis ? (amber ? "amber" : "green") : "red";
    state.approaches[d].remaining = state.phaseRemaining;
  }
}

export class Simulator {
  private intersections: IntersectionState[] = [];
  private vehicles: Vehicle[] = [];
  private tick = 0;
  private interval: ReturnType<typeof setInterval> | null = null;
  private subscribers = new Set<(s: SimSnapshot) => void>();
  private nextVehicleId = 1;
  private emergencyRoute: { intersectionIds: string[]; axis: "NS" | "EW" } | null = null;

  constructor(configs: IntersectionConfig[] = []) {
    this.load(configs);
  }

  load(configs: IntersectionConfig[]) {
    this.intersections = configs.map(configToState);
    for (const i of this.intersections) setLights(i);
    this.vehicles = [];
    this.tick = 0;
  }

  setAlgorithm(intersectionId: string, algo: Algorithm) {
    const i = this.intersections.find((x) => x.id === intersectionId);
    if (i) i.algorithm = algo;
  }

  setGlobalAlgorithm(algo: Algorithm) {
    for (const i of this.intersections) i.algorithm = algo;
  }

  /** Manual override: force a specific axis green now. */
  manualOverride(intersectionId: string, axis: "NS" | "EW") {
    const i = this.intersections.find((x) => x.id === intersectionId);
    if (!i) return;
    i.phase = axis;
    i.phaseRemaining = FIXED_GREEN;
    setLights(i);
  }

  /** Trigger emergency mode: cascade green along a list of intersections on one axis. */
  triggerEmergency(intersectionIds: string[], axis: "NS" | "EW") {
    this.emergencyRoute = { intersectionIds, axis };
    for (const id of intersectionIds) {
      const i = this.intersections.find((x) => x.id === id);
      if (!i) continue;
      i.emergencyOverride = true;
      i.phase = axis;
      i.phaseRemaining = 20;
      setLights(i);
    }
    // Inject an ambulance into the first intersection on the chosen axis.
    if (intersectionIds.length > 0) {
      const dir: Direction = axis === "NS" ? "S" : "W";
      const dest: Direction = axis === "NS" ? "N" : "E";
      this.vehicles.push({
        id: `amb-${this.nextVehicleId++}`,
        intersectionId: intersectionIds[0],
        direction: dir,
        speed: 16,
        destination: dest,
        waitingTime: 0,
        priority: 10,
        offset: -120,
      });
    }
  }

  clearEmergency() {
    if (!this.emergencyRoute) return;
    for (const id of this.emergencyRoute.intersectionIds) {
      const i = this.intersections.find((x) => x.id === id);
      if (i) i.emergencyOverride = false;
    }
    this.emergencyRoute = null;
  }

  start() {
    if (this.interval) return;
    this.interval = setInterval(() => this.step(), TICK_MS);
  }

  stop() {
    if (this.interval) clearInterval(this.interval);
    this.interval = null;
  }

  reset() {
    this.stop();
    for (const i of this.intersections) {
      i.passed = 0;
      i.totalWaitSeconds = 0;
      i.phase = "NS";
      i.phaseRemaining = FIXED_GREEN;
      for (const d of DIRECTIONS) {
        i.approaches[d].queueLength = 0;
      }
      setLights(i);
    }
    this.vehicles = [];
    this.tick = 0;
    this.emit();
  }

  subscribe(fn: (s: SimSnapshot) => void) {
    this.subscribers.add(fn);
    fn(this.snapshot());
    return () => this.subscribers.delete(fn);
  }

  snapshot(): SimSnapshot {
    return {
      tick: this.tick,
      timestamp: Date.now(),
      intersections: this.intersections.map((i) => ({
        ...i,
        approaches: { ...i.approaches },
      })),
      vehicles: this.vehicles.slice(),
      stats: this.computeStats(),
    };
  }

  private emit() {
    const snap = this.snapshot();
    this.subscribers.forEach((s) => s(snap));
  }

  private computeStats(): SimStats {
    const totalVehicles =
      this.vehicles.length +
      this.intersections.reduce(
        (acc, i) =>
          acc + DIRECTIONS.reduce((a, d) => a + i.approaches[d].queueLength, 0),
        0,
      );
    const vehiclesPassed = this.intersections.reduce((a, i) => a + i.passed, 0);
    const totalWait = this.intersections.reduce((a, i) => a + i.totalWaitSeconds, 0);
    const avgWait = vehiclesPassed > 0 ? totalWait / vehiclesPassed : 0;
    const queueSum = this.intersections.reduce(
      (a, i) => a + DIRECTIONS.reduce((b, d) => b + i.approaches[d].queueLength, 0),
      0,
    );
    const congestion = Math.min(1, queueSum / (this.intersections.length * MAX_QUEUE));
    return {
      totalVehicles,
      vehiclesPassed,
      avgWaitSeconds: avgWait,
      congestionScore: congestion,
      emergencyActive: this.emergencyRoute !== null,
    };
  }

  private step() {
    this.tick += 1;
    const dt = 1 / TICK_HZ;

    for (const inter of this.intersections) {
      // 1. Random arrivals
      for (const d of DIRECTIONS) {
        if (Math.random() < ARRIVAL_LAMBDA * dt) {
          if (inter.approaches[d].queueLength < MAX_QUEUE) {
            inter.approaches[d].queueLength += 1;
          }
        }
      }

      // 2. Accumulate wait for queued vehicles
      for (const d of DIRECTIONS) {
        inter.totalWaitSeconds += inter.approaches[d].queueLength * dt;
      }

      // 3. Discharge on green
      const greenAxis: "NS" | "EW" =
        inter.phase === "NS" || inter.phase === "NS_AMBER" ? "NS" : "EW";
      const isGreen = !inter.phase.endsWith("AMBER");
      if (isGreen) {
        const dirs: Direction[] = greenAxis === "NS" ? ["N", "S"] : ["E", "W"];
        for (const d of dirs) {
          const removable = Math.min(
            inter.approaches[d].queueLength,
            DISCHARGE_RATE * dt * (inter.emergencyOverride ? 2 : 1),
          );
          // Fractional discharge: track via random rounding
          const whole = Math.floor(removable);
          const frac = removable - whole;
          const extra = Math.random() < frac ? 1 : 0;
          const out = whole + extra;
          if (out > 0) {
            inter.approaches[d].queueLength -= out;
            inter.passed += out;
          }
        }
      }

      // 4. Phase countdown / algorithm switch
      inter.phaseRemaining -= dt;
      if (inter.phaseRemaining <= 0) {
        this.advancePhase(inter);
      }
      setLights(inter);
    }

    // 5. Move ambulances along their axis
    this.vehicles = this.vehicles.flatMap((v) => {
      const inter = this.intersections.find((i) => i.id === v.intersectionId);
      if (!inter) return [];
      v.offset += v.speed * dt;
      if (v.offset > 120) {
        // Vehicle cleared the intersection
        if (v.priority >= 10) {
          // Move to next intersection on emergency route, if any
          const route = this.emergencyRoute;
          if (route) {
            const idx = route.intersectionIds.indexOf(v.intersectionId);
            const next = route.intersectionIds[idx + 1];
            if (next) {
              v.intersectionId = next;
              v.offset = -120;
              return [v];
            }
            // End of route → clear emergency
            this.clearEmergency();
          }
        }
        return [];
      }
      return [v];
    });

    this.emit();
  }

  private advancePhase(inter: IntersectionState) {
    switch (inter.phase) {
      case "NS":
        inter.phase = "NS_AMBER";
        inter.phaseRemaining = AMBER_DURATION;
        break;
      case "NS_AMBER":
        inter.phase = "EW";
        inter.phaseRemaining = this.computeGreenDuration(inter, "EW");
        break;
      case "EW":
        inter.phase = "EW_AMBER";
        inter.phaseRemaining = AMBER_DURATION;
        break;
      case "EW_AMBER":
        inter.phase = "NS";
        inter.phaseRemaining = this.computeGreenDuration(inter, "NS");
        break;
    }
  }

  private computeGreenDuration(inter: IntersectionState, axis: "NS" | "EW"): number {
    if (inter.emergencyOverride) return 20;
    if (inter.algorithm === "fixed") return FIXED_GREEN;
    // greedy: green time proportional to total queue on this axis
    const dirs: Direction[] = axis === "NS" ? ["N", "S"] : ["E", "W"];
    const q = dirs.reduce((a, d) => a + inter.approaches[d].queueLength, 0);
    const dur = GREEDY_MIN_GREEN + q * 2;
    return Math.max(GREEDY_MIN_GREEN, Math.min(GREEDY_MAX_GREEN, dur));
  }
}

// Global singleton — survives HMR for smooth dev experience.
declare global {
  // eslint-disable-next-line no-var
  var __traffic_simulator: Simulator | undefined;
}
export const simulator: Simulator =
  globalThis.__traffic_simulator ?? (globalThis.__traffic_simulator = new Simulator());
